# Generated by Django 5.1.3 on 2025-01-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
