# Generated by Django 5.1.3 on 2025-01-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_division_slug_subtopic_slug_topic_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
