# Generated by Django 5.1.3 on 2025-01-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_chapter_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alias',
            field=models.CharField(default='cm', max_length=20),
            preserve_default=False,
        ),
    ]
