# Generated by Django 5.1.3 on 2025-01-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_course_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='alias',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
