# Generated by Django 5.1.3 on 2025-01-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_course_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='alias',
        ),
    ]
